# This GitHub action can publish assets for release when a tag is created.
# Currently its setup to run on any tag that matches the pattern "v*" (ie. v0.1.0).
#
# This uses an action (hashicorp/ghaction-import-gpg) that assumes you set your
# private key in the `GPG_PRIVATE_KEY` secret and passphrase in the `PASSPHRASE`
# secret. If you would rather own your own GPG handling, please fork this action
# or use an alternative one for key handling.
#
# You will need to pass the `--batch` flag to `gpg` in your signing step
# in `goreleaser` to indicate this is being used in a non-interactive mode.
#
name: release
on:
  push:
    tags:
      - "*"
jobs:
  goreleaser:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Import GPG key
        id: import_gpg
        uses: absaoss/ghaction-import-gpg@main
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --skip-publish
        env:
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.keyid }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: k0da/tf-registry-action@master
        with:
          token: ${{ secrets.GH_REG_TOKEN }}
          artifacts_dir: dist
          repository: k0da.github.io
          namespace: foo
          gpg_keyid: ${{ steps.import_gpg.outputs.keyid }}
          gpg_ascii_armor: ${{ steps.import_gpg.outputs.pub_ascii_armor }}
